[cmd/edit] fix: show info instead of error message when nothing to commit
Previously, there was an error message if the user did not made any
changes in the `description.md`:

```
$ git issue edit 1
Error: Git commit failed:
```

This is wrong, because it is allowed
to abord the edit.

Now there is an info:

```
$ git issue edit 1
Info: Nothing to commit
```

Signed-off-by: Timon Burkard <burkard.timon@gmail.com>